### ISSUE TITLE
The whole module is not working now

### ISSUE THREAD

**Issue by tanDjent** [HelKyle/antd-multi-cascader#10]
Last time forgot to restart the server 
TypeError: Cannot read property '_context' of undefined
getting this error on the latest version the older version is still working

**Comment by tanDjent** [comment]
could it be some dependency problem or something else because I know it is working on codesandbox

**Comment by tanDjent** [comment]
at Object.useContext (react.development.js:1446)
    at MultiCascader.js:69

**Comment by tanDjent** [comment]
Found the exact problem, it's the version of Antd
I'm using 4.6.1 
which doesn't have that context thing

**Comment by tanDjent** [comment]
Is there anything I can do to make it work on an older version of Antd ?

**Comment by cyancity** [comment]
try to fork the code and modify the dependencies

**Comment by tanDjent** [comment]
I instead tried updating antd first but the dropdown was still moving with the main scroll bar

**Comment by HelKyle** [comment]
Fixed, please try `antd-multi-cascader@1.1.1`

**Comment by HelKyle** [comment]
> Last time forgot to restart the server
> TypeError: Cannot read property '_context' of undefined
> getting this error on the latest version the older version is still working

Have been fixed in `antd-multi-cascader@1.1.1`

**Comment by HelKyle** [comment]
> I instead tried updating antd first but the dropdown was still moving with the main scroll bar

If you provide a minimal online demo using code sandbox, I'd willing to help you out.

**Comment by HelKyle** [comment]
I have downgrade the antd version to 4.6.1 and it works just fine. [https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx](https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx)

**Comment by tanDjent** [comment]
oh thank you 
Checking the latest version

**Comment by tanDjent** [comment]
okay, everything is working great now!!! 
Thank you so much for your hard work
