### ISSUE TITLE
Not exactly an issue just suggestion, to add maxTagCount and check on text click

### ISSUE THREAD

**Issue by tanDjent** [HelKyle/antd-multi-cascader#12]
There's an attribute called maxTagCount in antd Select which lets you select the number of tags that can be displayed it would be helpful if that was present here because as of right now if there are multiple tags selected and the component has a fixed width and height then the tags will either overflow or there will be a scrollbar inside the component.
And the other would be a quality of life change, to select a checkbox currently the user has to click on the checkbox it won't work if someone clicked on the text, it would be better if the user could click on the text as well to check the checkbox.

**Comment by HelKyle** [comment]
Here you go~ `antd-multi-cascader@1.2.0`

**Comment by tanDjent** [comment]
Thank you, Kind Sir!!!

**Comment by tanDjent** [comment]
The latest update has created another issue-  on removing one tag all the tags are getting removed and the value is being set to an empty array.

**Comment by HelKyle** [comment]
> The latest update has created another issue- on removing one tag all the tags are getting removed and the value is being set to an empty array.

Sorry about that, I will fix it as quick as possible

**Comment by HelKyle** [comment]
Bug fixed at `antd-multi-cascader@1.2.1`

**Comment by tanDjent** [comment]
sorry I feel ashamed asking these things again and again but can you also add dropdownMatchSelectWidth from antd Select 
it will fix one of the css issues of the dropdown 
and if you can also add dropdownClassName later it will be great 
but the dropdownMatchSelectWidth is the most important one
