### ISSUE TITLE
能说明下isLeaf的作用吗？

### ISSUE THREAD

**Issue by KingGanZeng** [HelKyle/antd-multi-cascader#16]
如题

**Comment by HelKyle** [comment]
为了异步数据加载的时候用来判断是否有 children，如果不需要异步加载数据就用不到。

```js
const hasChildren = (children && children.length > 0) || isLeaf === false
```

**Comment by KingGanZeng** [comment]
感谢解答，我还有另一个问题：1.3.0似乎出现了打开后无法选中元素的问题，1.1.1是好的。

似乎是这个属性引起的，但是隐藏之后虽然可以选中，cascader却无法关闭了
<img width="1061" alt="屏幕快照 2021-05-02 下午5 13 48" src="https://user-images.githubusercontent.com/22743840/116808179-fed1a500-ab69-11eb-884f-c4955b1bccc5.png">

**Comment by HelKyle** [comment]
> 感谢解答，我还有另一个问题：1.3.0似乎出现了打开后无法选中元素的问题，1.1.1是好的。
> 
> 似乎是这个属性引起的，但是隐藏之后虽然可以选中，cascader却无法关闭了
> <img alt="屏幕快照 2021-05-02 下午5 13 48" width="1061" src="https://user-images.githubusercontent.com/22743840/116808179-fed1a500-ab69-11eb-884f-c4955b1bccc5.png">

你使用的 antd 版本是多少呢？可能需要手动加上 `popupTransitionName={'ant-slide-up'}` 属性

**Comment by KingGanZeng** [comment]
> > 感谢解答，我还有另一个问题：1.3.0似乎出现了打开后无法选中元素的问题，1.1.1是好的。
> > 似乎是这个属性引起的，但是隐藏之后虽然可以选中，cascader却无法关闭了
> > <img alt="屏幕快照 2021-05-02 下午5 13 48" width="1061" src="https://user-images.githubusercontent.com/22743840/116808179-fed1a500-ab69-11eb-884f-c4955b1bccc5.png">
> 
> 你使用的 antd 版本是多少呢？可能需要手动加上 `popupTransitionName={'ant-slide-up'}` 属性

👍👍可以了，没有注意翻文档。优秀的组件。
另：className的type貌似写错了。

**Comment by HelKyle** [comment]
嗯，文档上 className 类型写错了，我更新一下
