### ISSUE TITLE
不能收起来呢？

### ISSUE THREAD

**Issue by Mluocheng** [HelKyle/antd-multi-cascader#24]
点击 取消或者确定 或者其他地方都不能收起来呢？？？
![image](https://user-images.githubusercontent.com/31057183/128658276-7d56be76-648f-4223-8efa-ea29c4c75f6f.png)

**Comment by HelKyle** [comment]
可以提供一个在线的 demo 吗？感觉是 antd 版本的问题 https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx

**Comment by Mluocheng** [comment]
看了其他issues ，  
使用
<MultiCascader
  popupTransitionName="ant-slide-up"
/>

popupTransitionName="ant-slide-up"

这个属性解决了该问题。

**Comment by Mluocheng** [comment]
应该和 https://github.com/HelKyle/antd-multi-cascader/issues/4  这个是同一个问题， 属性的问题我是通过css 来解决的。
:global{
  .antd-multi-cascader {
    pointer-events: auto !important;
  }
}
