### ISSUE TITLE
Menu无法点击

### ISSUE THREAD

**Issue by zhouhuan327** [HelKyle/antd-multi-cascader#26]
在antd4.13.0及以上的环境下,下拉菜单会不可点击,并且无法收起

**Comment by zhouhuan327** [comment]
在antd 4.13.0 中有一项改动

> 动画相关 css className 全部添加 ant- 前缀以防止重名问题。 [#29268](https://github.com/ant-design/ant-design/pull/29268)

使得下拉菜单动画从slide-up 变成了 ant-slide-up

Trigger传入错误的popupTransitionName 会导致popup无法被点击

**Comment by HelKyle** [comment]
> 在antd 4.13.0 中有一项改动
> 
> > 动画相关 css className 全部添加 ant- 前缀以防止重名问题。 [#29268](https://github.com/ant-design/ant-design/pull/29268)
> 
> 使得下拉菜单动画从slide-up 变成了 ant-slide-up
> 
> Trigger传入错误的popupTransitionName 会导致popup无法被点击

确实有这个问题，组件支持传入 `popupTransitionName` 参数的哈，你可以试一下。后面发个新版本改成默认是 `ant-slide-up`
