### ISSUE TITLE
在antd3 react17 情况下使用antd-multi-cascader 1.3.0 要报错

### ISSUE THREAD

**Issue by songuu** [HelKyle/antd-multi-cascader#28]
Cannot read properties of undefined (reading '_context')

**Comment by HelKyle** [comment]
如果你使用的 antd 版本小于 4.13.0，请安装 1.3.0 的版本，或手动设置 popupTransitionName=slide-up

**Comment by HelKyle** [comment]
原因好像是 antd3 没有 ConfigContext，要不升级下 antd 大版本？

**Comment by songuu** [comment]
应该升级不了，我可以研究下，然后重写一次就行了。

**Comment by HelKyle** [comment]
我把 context 相关的代码删了，你可以再试一下吗？ `1.3.1`

**Comment by songuu** [comment]
好的，麻烦了

**Comment by songuu** [comment]
使用了"antd": "3.26.19", "antd-multi-cascader": "1.3.1", 还是会报错

Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by HelKyle** [comment]
在本地没复现出来，倒是发现新的问题，antd3/4 的样式类名不兼容，展示出来有问题。

**Comment by songuu** [comment]
https://codesandbox.io/s/dreamy-jennings-2y1ff-forked-p9ms1?file=/src/App.tsx
