### ISSUE TITLE
能否支持Antd TreeSelect的showCheckedStrategy属性呢?

### ISSUE THREAD

**Issue by zhouhuan327** [HelKyle/antd-multi-cascader#29]
antd的树选择器有三种选中策略:
TreeSelect.SHOW_ALL: 显示所有选中节点(包括父节点)。
TreeSelect.SHOW_PARENT: 只显示父节点(当父节点下所有子节点都选中时)。
TreeSelect.SHOW_CHILD: 默认只显示子节点

期望支持SHOW_CHILD,选中父节点时只展示所有叶子节点,并且组件的值也是所有叶子节点value

虽然现在可以通过ref拿到matchAllLeafValue方法,但是每次都得调用比较麻烦.

**Comment by HelKyle** [comment]
考虑用 antd 4.17.0 吧，这个仓库仅作为学习参考保留   
https://ant.design/components/cascader/#components-cascader-demo-multiple
