### ISSUE TITLE
data变化时没有重新渲染

### ISSUE THREAD

**Issue by GitHdu** [HelKyle/antd-multi-cascader#3]
例如默认是空数组，请求回来的数据传给data还是空数组，导致点击展开菜单报错

**Comment by HelKyle** [comment]
收到，我看下怎么处理

**Comment by HelKyle** [comment]
展开报错的问题已修复，Demo: https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx

**Comment by GitHdu** [comment]
> 展开报错的问题已修复，Demo: https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx

可以支持搜索吗

**Comment by HelKyle** [comment]
> 可以支持搜索吗

暂时没有想法，有兴趣的话可以提 MR 哈
