### ISSUE TITLE
点击select框触发子集弹层的时候，元素新增了pointer-events: none;属性导致无法选中

### ISSUE THREAD

**Issue by shuqianchi** [HelKyle/antd-multi-cascader#4]
rt

**Comment by HelKyle** [comment]
啥意思？没看懂

**Comment by shuqianchi** [comment]
在
    "antd": "^4.13.0",
    "antd-multi-cascader": "^0.0.11",
    "react": "^17.0.1"
版本下
组件的点击事件失效

**Comment by HelKyle** [comment]
> 在
> "antd": "^4.13.0",
> "antd-multi-cascader": "^0.0.11",
> "react": "^17.0.1"
> 版本下
> 组件的点击事件失效

Hi, 原因是在 `antd 4.13.0` 版本上 `rc-trigger` 这个组件有 breaking change。解决方法是使用时需要手动给 `popupTransitionName` 赋值 `ant-slide-up`

```js
<MultiCascader
  popupTransitionName="ant-slide-up"
/>
```

**Comment by HelKyle** [comment]
试一下 `antd-multi-cascader@0.1.1`
