### ISSUE TITLE
在 index.tsx 上导出 Props 接口

### ISSUE THREAD

**Issue by nekocode** [HelKyle/antd-multi-cascader#7]
![image](https://user-images.githubusercontent.com/4783781/113257261-f2ed8b80-92fc-11eb-9a9e-838557f873f5.png)

Hi，请问能把组件的参数接口在根 index 导出一下么？否则我只能像上图一样从内部路径导入

**Comment by HelKyle** [comment]
可以的，骚等我一下

**Comment by HelKyle** [comment]
`1.0.1` 试一下呢

**Comment by nekocode** [comment]
thx!
