### ISSUE TITLE
Dropdown is moving with the main scroll bar 

### ISSUE THREAD

**Issue by tanDjent** [HelKyle/antd-multi-cascader#8]
The whole dropdown moves when the main scrollbar of the page is used.
No prop called getPopupContainer can be passed like in Antd components to fix this issue.

**Comment by HelKyle** [comment]
Will fix it right await, wait a minute.

**Comment by HelKyle** [comment]
Done, have a try `antd-multi-cascader@1.1.0`

**Comment by tanDjent** [comment]
Dude, this is great your work is helping me and many others
one more thing can you also add the maxTagCount prop from Select
if the number of tags more than the container can display they start overflowing out of the container

**Comment by HelKyle** [comment]
> Dude, this is great your work is helping me and many others
> one more thing can you also add the maxTagCount prop from Select
> if the number of tags more than the container can display they start overflowing out of the container

Ok, will add this props if I have time in the future
