### ISSUE TITLE
getPopupContainer is not working 

### ISSUE THREAD

**Issue by tanDjent** [HelKyle/antd-multi-cascader#9]
index.js:1406 Warning: React does not recognize the `getPopupContainer` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `getpopupcontainer` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Selector)
    in Selector (created by ForwardRef)
    in Trigger (created by ForwardRef)
    in ForwardRef
    in ForwardRef (created by ForwardRef)
    in Provider (created by ForwardRef)

**Comment by HelKyle** [comment]
Please make sure you are using the latest version. View the online demo here: [https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx](https://codesandbox.io/s/dreamy-jennings-2y1ff?file=/src/App.tsx)

**Comment by HelKyle** [comment]
Feel free to reopen if the issue still exists after reinstall.
